b_deformation:
  model: "../../Data/checkpoints/biotac_mesh_reconstruction/biotac_batch_size_128_kl_weight_0.005_cheb_order_6:z_128_lr_0.001_L_1_seed_76979_fem_VAE_allData/epoch=299-step=288300.ckpt"
  norm: "../../Data/datasets/processed/biotac_155605_dist_1_20_env_0_1_2_3_4_5_6_7_8_norm.pt"
b_signal:
  model: "../../Data/checkpoints/biotac_signal_reconstruction/all_data/epoch=323-step=248832.ckpt"
  norm: "../../Data/datasets/biotac_signal_norms/value_norms_all_data.pt"

postfix: "all_data"