defaults:
  - _self_
  - checkpoints: all_data

hydra:
  run:
    dir: logs/outputs/${now:%Y-%m-%d-%H-%M-%S}

datasets:
  data:
    train: [
      ["../../Data/datasets/BioTac_Pure_Exp_Dataset/nvidia_train_data.hdf5",
       "../../Data/datasets/BioTac_Pure_Exp_Dataset/nvidia_train_data_simulated.hdf5"
      ]
    ]
    test: [
      "../../Data/datasets/BioTac_Pure_Exp_Dataset/nvidia_test_data.hdf5",
      "../../Data/datasets/BioTac_Pure_Exp_Dataset/nvidia_test_data_simulated.hdf5"
    ]

settings:
  id_filter: null
  depth_filter: 0.002
  result_postfix: "depth_filter_surface_adjusted"
  result_folder: "../../Data/datasets/value_def_dataset"