batch_size: 1024
lr: 0.001
num_layers: 4
weight_decay: 0
lr_decay: 1
num_neurons_layer_0: 512
activation_layer_0: ELU
dropout_layer_0: 0.2
num_neurons_layer_1: 1024
activation_layer_1: ELU
dropout_layer_1: 0.4
num_neurons_layer_2: 1024
activation_layer_2: ELU
dropout_layer_2: 0.0
num_neurons_layer_3: 256
activation_layer_3: ELU
dropout_layer_3: 0.0

# {'batch_size': 128, 'lr': 0.0001, 'num_layers': 4, 'weight_decay': 1e-05, 'lr_decay': 1, 'num_neurons_layer_0': 768, 'activation_layer_0': 'ELU', 'dropout_layer_0': 0.4, 'num_neurons_layer_1': 1280, 'activation_layer_1': 'ReLU', 'dropout_layer_1': 0.4, 'num_neurons_layer_2': 2688, 'activation_layer_2': 'LeakyReLU', 'dropout_layer_2': 0.4, 'num_neurons_layer_3': 3584, 'activation_layer_3': 'ReLU', 'dropout_layer_3': 0.3}